version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_creditos
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: creditosdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mariadb:
    image: mariadb:10.11
    container_name: mariadb_creditos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: creditosdb
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  pgdata:
  mariadbdata:
